# Generated by Django 3.2.16 on 2024-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='output',
            field=models.FileField(null=True, upload_to='output'),
        ),
    ]
