# Generated by Django 3.2.16 on 2024-06-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_processedimage_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
