# Generated by Django 3.2.16 on 2024-06-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
